
- name: set zk configs
  template: src={{ item }}.j2 dest=/etc/kafka/{{ item }} mode=0644
  with_items:
    - zookeeper_client_jaas.conf
    - zookeeper-env.sh
    - zookeeper_jaas.conf
    - zookeeper.properties
