- selinux:
    state: disabled

- name: Install EPEL repo
  yum: name=epel-release update_cache=yes state=present
  become: true

- name: install base packages
  yum: name={{ item }} state=present update_cache=yes
  become: true
  with_items:
    - htop
    - curl
    - wget
    - ntp
    - tree
    - lsof
    - screen
    - jq
    - krb5-workstation

- name: Install java openjdk
  yum: name=java-1.8.0-openjdk update_cache=yes state=present
  become: true

- name: Create group for Kafka user
  group: name={{ item }} state=present
  with_items:
    - confluent
    - readers
    - writers

- name: Create users
  user: name={{ item.n }} group={{ item.g }}
  with_items:
    - { n: "confluent", g: "confluent" }
    - { n: "kafka", g: "confluent" }
    - { n: "reader", g: "readers" }
    - { n: "writer", g: "writers" }
    - { n: "zookeeper", g: "confluent"}

- name: create confluent-kafka related directories
  file: path={{ item.path }} state=directory owner=confluent group=confluent mode=0755 recurse=yes
  with_items:
    - { path: "/var/lib/kafka", owner: "confluent" }

- name: check if confluent target dir exists
  stat:
    path: /opt/confluent/bin
  register: optconfluent

- name: extract the confluent source tar.gz
  unarchive:
    src: /resources/confluent-oss-3.2.1-2.11.tar.gz
    dest: /opt/
    remote_src: True
  when: optconfluent.stat.exists==false

- name: create confluent related symlinks
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
    owner=confluent group=confluent
    force=yes
    remote_src=True
  with_items:
    - { dest: '/opt/confluent', src: '/opt/confluent-3.2.1/' }
    - { dest: '/etc/kafka', src: '/opt/confluent/etc/kafka/' }
    - { dest: '/etc/kafka-rest', src: '/opt/confluent/etc/kafka-rest/' }
    - { dest: '/etc/schema-registry', src: '/opt/confluent/etc/schema-registry/' }

- name: create confluent log dir
  file: path={{ item.path }} state=directory owner=confluent group=confluent mode=0755 recurse=yes
  with_items:
    - { path: "/opt/confluent/logs", owner: "confluent" }

- name: create symlink to confluent log
  file: src=/opt/confluent/logs dest=/var/log/kafka state=link owner=confluent remote_src=true

- name: copy confluent-stack env. script to profile.d
  template: src=confluent-stack.sh.j2 dest=/etc/profile.d/confluent-stack.sh mode=0644

- name: set kafka client configs
  template: src={{ item }}.j2 dest=/etc/kafka/{{ item }} mode=0644
  with_items:
    - kafka_client_jaas.conf
    - client-gssapi.properties
    - client-plain.properties
    - kafka-env.sh

- name: set kerberos client configs
  template: src=krb5.conf.j2 dest=/etc/krb5.conf mode=0644

- name: strip hosts file
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: '^127\.0\.0\.1\t(?!localhost).*'
