- selinux:
    state: disabled

- name: Install EPEL repo
  yum: name=epel-release update_cache=yes state=present
  become: true

- name: install base packages
  yum: name={{ item }} state=present update_cache=yes
  become: true
  with_items:
    - htop
    - curl
    - wget
    - ntp

- name: Install java openjdk
  yum: name=java-1.8.0-openjdk update_cache=yes state=present
  become: true

- name: Create group for Kafka user
  group: name=confluent state=present
  become: true
- name: Create user
  user: name=confluent group=confluent
  become: true
- name: create confluent-kafka related directories
  file: path={{ item.path }} state=directory owner=confluent group=confluent mode=0755 recurse=yes
  with_items:
    - { path: "/var/log/kafka", owner: "confluent" }
    - { path: "/var/lib/kafka", owner: "confluent" }
    - { path: "/var/lib/zookeeper", owner: "confluent" }

- name: extract the confluent source tar.gz
  unarchive:
    src: /resources/confluent-oss-3.2.1-2.11.tar.gz
    dest: /opt/
    remote_src: True
- name: create sample 'end-'users
  user: name={{ item }}
  with_items:
    - reader
    - writer

- name: Install java openjdk
  yum: name=java-1.8.0-openjdk update_cache=yes state=present
  become: true

- name: create confluent related symlinks
  file:
    src={{ item.src }}
    dest={{ item.dest }}
    state=link
    owner=confluent group=confluent
    force=yes
    remote_src=True
  with_items:
    - { dest: '/opt/confluent', src: '/opt/confluent-3.2.1/' }
    - { dest: '/etc/kafka', src: '/opt/confluent/etc/kafka/' }
    - { dest: '/etc/kafka-rest', src: '/opt/confluent/etc/kafka-rest/' }
    - { dest: '/etc/schema-registry', src: '/opt/confluent/etc/schema-registry/' }
    - { dest: '/usr/bin/kafka-avro-console-consumer', src: '/opt/confluent/bin/kafka-avro-console-consumer' }
    - { dest: '/usr/bin/kafka-avro-console-producer', src: '/opt/confluent/bin/kafka-avro-console-producer' }
    - { dest: '/usr/bin/kafka-console-consumer', src: '/opt/confluent/bin/kafka-console-consumer' }
    - { dest: '/usr/bin/kafka-console-producer', src: '/opt/confluent/bin/kafka-console-producer' }
    - { dest: '/usr/bin/kafka-topics', src: '/opt/confluent/bin/kafka-topics' }
    - { dest: '/usr/bin/kafka-acls', src: '/opt/confluent/bin/kafka-acls' }

- name: Install Kerberos client packages
  package: name="{{ item }}" state=present
  with_items:
    - krb5-libs
    - krb5-workstation
- name: Copy krb5 configuration file
  template: src=krb5.conf.j2 dest=/etc/krb5.conf