- name: set Kafka rest config
  template: src=kafka-rest.properties.j2 dest=/etc/kafka-rest/kafka-rest.properties mode=0644

- name: set Kafka Rest jaas config
  template: src=kafka-rest_jaas.conf.j2 dest=/etc/kafka-rest/kafka-rest_jaas.conf mode=0644
