- name: systemdreload
  become: yes
  become_user: root
  command: systemctl daemon-reload

- name: enableRestproxyService
  become: yes
  become_user: root
  command: systemctl enable confluent-kafka-rest.service
