- name: set Kafka broker config
  template: src=server.properties.j2 dest=/etc/kafka/server.properties mode=0644 owner=confluent

- name: set broker jaas config
  template: src=kafka_server_jaas.conf.j2 dest=/etc/kafka/kafka_server_jaas.conf mode=0644 owner=confluent

- name: set broker start script
  template: src=start-kafka.sh.j2 dest=/usr/local/bin/start-kafka.sh mode=0644 owner=confluent
