---
- hosts: all
  roles:
    - common

- hosts: zookeepers
  roles:
    - zookeeper
    
- hosts: confluentmasters
  roles:
    - restproxy
    - schemaregistry

- hosts: workers
  roles:
    - kafkabroker
