---
- hosts: all
  roles:
    - common

- hosts: zookeepers
  roles:
    - zookeeper

- hosts: workers
  roles:
    - kafkabroker

- hosts: confluentmasters
  roles:
    - restproxy
    - schemaregistry

- hosts: edge-nodes
  roles:
    - kdc
